name: Build and Deploy

on:
  workflow_run:
    workflows: ['Build and Test']
    types:
      - completed
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      SITE_NAME: 'Access Insights Platform'
      SITE_ACRONYM: 'AIP'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Test
        uses: cypress-io/github-action@v2
        with:
          start: yarn serve
          wait-on: 'http://localhost:8000'

      - name: Deploy 🚀
        run: |
          cp ./dist/index.html ./dist/200.html
          npm install -g surge
          surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
