name: Build and Deploy

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
      SITE_NAME: 'Catalyst AIP'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cleanup
        run: yarn clean

      - name: Install and Build
        run: |
          yarn install
          yarn build

      - name: Test
        uses: cypress-io/github-action@v2
        with:
          start: yarn develop
          wait-on: 'http://localhost:8000'

      - name: Deploy 🚀
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          git remote set-url origin https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}
          yarn deploy
